### ISSUE TITLE
Nogo: cycle in dependency graph when building `genquery` targets

### ISSUE THREAD

**Issue by Illedran** [bazelbuild/rules_go#3883]
### What version of rules_go are you using?

`v0.46.0`

### What version of gazelle are you using?

No gazelle.

### What version of Bazel are you using?

`7.0.2`

### Does this issue reproduce with the latest releases of all the above?

Yes (`v0.46.0` and `7.0.2` are latest as of time of writing).

### What operating system and processor architecture are you using?

```
$ uname -srm
Linux 5.15.146.1-microsoft-standard-WSL2 x86_64
```

### Any other potentially useful information about your toolchain?

No bzlmod.

### What did you do?

When having `nogo` enabled, attempting to build a `genquery` whose expression references `go_*` rules fails due to a cycle in dependency graph.

`WORKSPACE`
```python
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "80a98277ad1311dacd837f9b16db62887702e9f1d1c4c9f796d0121a46c8e184",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.46.0/rules_go-v0.46.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.46.0/rules_go-v0.46.0.zip",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.22.1", nogo = "@io_bazel_rules_go//:tools_nogo")
```
`src/main.go`
```go
package main

import "fmt"

func main() {
    fmt.Println("Hello world!")
}
```
`src/BUILD.bazel`
```python
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "src_lib",
    srcs = ["main.go"],
)

go_binary(
    name = "src",
    embed = [":src_lib"],
)

genquery(
    name = "src_genquery",
    expression = "deps(//src)",
    scope = [":src"],
)
```

```
$ bazel build src:src_genquery
ERROR: /home/illedran/.cache/bazel/_bazel_illedran/a3b41e2226cf2286c26d4e18a5d6a010/external/io_bazel_rules_go/BUILD.bazel:71:16: in go_context_data rule @@io_bazel_rules_go//:go_context_data: cycle in dependency graph:
    //src:src_genquery (c996bfa92bcafc2798baf4dbf854da936ce6f49485d19b67b34b429667416404)
    //src:src_genquery (312a038fde71b14d7680a2d5856ddfa0ee2fb821b1f2d44cc703454abe09284c)
    //src:src
.-> @@io_bazel_rules_go//:go_context_data
|   @@io_bazel_rules_nogo//:nogo
|   @@io_bazel_rules_go//:tools_nogo
|   @@io_bazel_rules_go//:tools_nogo_actual
|   @@io_bazel_rules_go//go/tools/builders:nogo_srcs
|   @@org_golang_x_tools//internal/facts:facts
`-- @@io_bazel_rules_go//:go_context_data
ERROR: Analysis of target '//src:src_genquery' failed; build aborted
```

Same example as above is also available at https://github.com/Illedran/nogo_genquery_bug.

**Comment by fmeum** [comment]
I think that we can fix this if we decide to drop compatibility with Bazel 6, see https://github.com/bazelbuild/rules_go/blob/d45e218910fbecb00867e3a4dde3fe14d4a1e00a/go/private/BUILD.bazel#L179-L180

@tyler-french @linzhp What do you think, are we ready for this?

**Comment by linzhp** [comment]
We ran into this issue when upgrading to rules_go 0.29 in Nov 2021, before Bazel 6 was available. The solution was to create an aspect instead.

I am afraid it's still too early to drop compatibility with Bazel 6, when Bazel 7 was only 3 month old.

**Comment by fmeum** [comment]
@linzhp Sorry I meant dropping support for Bazel 5, i.e., exclusively supporting Bazel 6 and higher.

**Comment by linzhp** [comment]
That sounds more reasonable. I am fine with dropping Bazel 5 support.

**Comment by philipuvarov** [comment]
@linzhp @fmeum Hello! Running into the same issue here. Is there a known work-around for that? Right now, it, unfortunately, blocks adoption of the nogo rules in my project

**Comment by fmeum** [comment]
I looked into this a bit more and it turns out to be a known Bazel issue (https://github.com/bazelbuild/bazel/issues/14169). I have pinged it and will try to work on a fix. 

The recommended workarounds include using an aspect instead or running `bazel query` outside of Bazel. As this is not something we can work around on the rules_go side, I will close the rules_go issue.

**Comment by be9** [comment]
I've stumbled upon this problem today with rules_go 0.57. Bazel 5 support has already been dropped. Is there a chance for this issue to be fixed?

**Comment by fmeum** [comment]
I have fixed the issue in Bazel 7.3.0 and higher. Bazel 6 will become unsupported soon.

**Comment by be9** [comment]
@fmeum we're on Bazel 7.6.1 and I still get something along these lines:

```
$ bazel build //services/locksmith:locksmith_deps
WARNING: Build option --test_env has changed, discarding analysis cache (this can be expensive, see https://bazel.build/advanced/performance/iteration-speed).
ERROR: /private/var/tmp/_bazel_odashevskii/5431e55af24f3f4453d7a47c2ed26096/external/io_bazel_rules_go/BUILD.bazel:72:16: in go_context_data rule @@io_bazel_rules_go//:go_context_data: cycle in dependency graph:
    //services/locksmith:locksmith_deps (71d65e675f6cc11b2ed566db4e8f263c6789f6675fca4ee70e06d4f0670cded9)
    //services/locksmith:locksmith_deps (4c1ce9820741a9fde86397983b9068f40df8e57fbed70e1e13659a2c776eac65)
    //services/locksmith:locksmith
.-> @@io_bazel_rules_go//:go_context_data
|   @@io_bazel_rules_nogo//:nogo
|   //lib/bazel/nogo:nogo
|   //lib/bazel/nogo:nogo_actual
|   @@com_github_pmezard_go_difflib//difflib:go_default_library
|   @@com_github_pmezard_go_difflib//difflib:difflib
`-- @@io_bazel_rules_go//:go_context_data
ERROR: Analysis of target '//services/locksmith:locksmith_deps' failed; build aborted
INFO: Elapsed time: 2.426s, Critical Path: 0.37s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```

the query is

```starlark
genquery(
    name = "locksmith_deps",
    expression = "deps(//services/locksmith:locksmith)",
    scope = ["//services/locksmith:locksmith"],
    opts = ["--notool_deps", "--noimplicit_deps"],
)
```

**Comment by fmeum** [comment]
@be9 I forgot to mention that you need to enable `--experimental_skip_ttvs_for_genquery` manually for Bazel 7, it became the default in 8.
